###
POST http://localhost:5000/api/result
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDliNzU5NmNjMDY1ZTUxNzQ4MzBiNTYiLCJpYXQiOjE2MjA5NjQ4Nzd9.VsRPLY0baRMgZIbADIw8ip5UfXIGsCee4zAEfMxAB7E

{
  "studentID": "BI9-157",
  "studentName": "Tran Thanh Long",
  "courseCode": "MATH 2.1",
  "courseName": "PROBABILITIES & STATISTICS",
  "lecturerName": "Tran Hoang Tung",
  "year": "2nd Year",
  "program":"Bachelor",
  "department": "ICT",
  "creditPoints": "3 ECTS",
  "attendance": "16",
  "exercises": "18",
  "assignment": "0",
  "reports": "0",
  "midterm": "18",
  "final": "18",
  "total": "18",
  "status": "pass",
  "date": "19/11/2019",
  "wave": "2019-2020"
}

### 
GET http://localhost:5000/api/result
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDliNzU5NmNjMDY1ZTUxNzQ4MzBiNTYiLCJpYXQiOjE2MjA5NjQ4Nzd9.VsRPLY0baRMgZIbADIw8ip5UfXIGsCee4zAEfMxAB7E

###
PUT http://localhost:5000/api/result/60a6acf23525244938701580
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDliNzU5NmNjMDY1ZTUxNzQ4MzBiNTYiLCJpYXQiOjE2MjA5NjQ4Nzd9.VsRPLY0baRMgZIbADIw8ip5UfXIGsCee4zAEfMxAB7E

{
  "studentID": "BI9-157",
  "StudentName": "Tran Thanh Long1",
  "courseCode": "MATH 2.1",
  "courseName": "PROBABILITIES & STATISTICS",
  "lecturerName": "Tran Hoang Tung",
  "year": "2nd Year",
  "program":"Bachelor",
  "department": "ICT",
  "evaluation":{
      "attendance": "16",
      "exercises": "18",
      "assignment": "0",
      "reports": "0",
      "midterm": "18",
      "final": "18",
      "total": "20"
  },
  "date": "19/11/2019",
  "wave": "2019-2020"
}

###
DELETE http://localhost:5000/api/result/60a6a785f2723c16f8f98ccb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDliNzU5NmNjMDY1ZTUxNzQ4MzBiNTYiLCJpYXQiOjE2MjA5NjQ4Nzd9.VsRPLY0baRMgZIbADIw8ip5UfXIGsCee4zAEfMxAB7E
