###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "id": "12",
    "username": "BI9-177",
    "password": "student",
    "userName": "Le Ho Nguyen",
    "role": "Student"
}

### 
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJmMzdiOTAyOTY1NTQ4NTgyMzllODMiLCJpYXQiOjE2MjMxNDQ0NjN9.UFLra4OGT0o3Vr2B9HOisKITK67uwdmwnHD7BgPPLLY

### 
PUT http://localhost:5000/api/user/60bf48d189d9ed457812a154
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJmMWJiOGI5MmFlNjU1MTRkYzFiYzYiLCJyb2xlIjoiU3RhZmYiLCJpYXQiOjE2MjMxMzc2OTR9.VIOlav5UpbTsbjJzSMVBOfk6iCjWtyY3PT4KR4hzU9g

{
    "username": "admin",
    "password": "admin",
    "userName": "Ha",
    "role": "Staff"
}

###
DELETE http://localhost:5000/api/user/60bf48d189d9ed457812a154
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU3MzN9.rllqYcqswZEtOsmuodX0OFTXJhj5C6N40nnuxW9TMmA

