###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "lecturer",
    "password": "lecturer",
    "userName": "Long",
    "role": "Lecturer"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "student",
    "password": "student"
}

### 
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJmMzdiOTAyOTY1NTQ4NTgyMzllODMiLCJpYXQiOjE2MjMxNDQ0NjN9.UFLra4OGT0o3Vr2B9HOisKITK67uwdmwnHD7BgPPLLY

### 
PUT http://localhost:5000/api/auth/60bf1bb8b92ae65514dc1bc6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJmMWJiOGI5MmFlNjU1MTRkYzFiYzYiLCJyb2xlIjoiU3RhZmYiLCJpYXQiOjE2MjMxMzc2OTR9.VIOlav5UpbTsbjJzSMVBOfk6iCjWtyY3PT4KR4hzU9g

{
    "username": "admin",
    "password": "admin",
    "role": "Lecturer"
}

###
DELETE http://localhost:5000/api/auth/60bf189d24d03165b4453f06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU3MzN9.rllqYcqswZEtOsmuodX0OFTXJhj5C6N40nnuxW9TMmA


###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU3MzN9.rllqYcqswZEtOsmuodX0OFTXJhj5C6N40nnuxW9TMmA

{
  "title": "test",
  "description": "Reac11t2",
  "url": "rea12312ct2.com",
  "status": "TO LEARN"
}


### 
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU2Njd9.oQtiYJAFDkVLksWAcmvg4utIXMO06_pHLaG936HKFCY

### 
PUT http://localhost:5000/api/posts/60b0aa7e1c34640e20b6fd84
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU3MzN9.rllqYcqswZEtOsmuodX0OFTXJhj5C6N40nnuxW9TMmA

{
  "title": "React Update 3 admin moi",
  "description": "Reac11t Update 3 ",
  "url": "rea12312ct.com Update 3",
  "status": "LEARNING"
}

###
DELETE http://localhost:5000/api/posts/60b7d5491e9b55052806a8b4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIwYTQxMTFjMzQ2NDBlMjBiNmZkODMiLCJpYXQiOjE2MjIxOTU3MzN9.rllqYcqswZEtOsmuodX0OFTXJhj5C6N40nnuxW9TMmA
